#include "backtesting/BacktestEngine.hpp"

#include <stdexcept>
#include <utility>

BacktestEngine::BacktestEngine(
    const PriceTable& prices,
    std::vector<double> target_weights,
    BacktestConfig config
) : prices_(prices), target_weights_(std::move(target_weights)), config_(config) {
    // Class invariant: one target weight is required for each asset.
    if (target_weights_.size() != prices_.asset_count()) {
        throw std::runtime_error("Target weight count does not match asset count.");
    }
}

BacktestResult BacktestEngine::run(const RebalanceStrategy& strategy) const {
    BacktestResult result;
    result.name = strategy.name();

    // Every strategy starts from the same initial portfolio.
    Portfolio portfolio(config_.initial_capital, prices_.asset_count());
    portfolio.invest_to_target(prices_.prices(0), target_weights_);

    // Record day 0 immediately after initial investment.
    result.dates.push_back(prices_.date(0));
    result.equity_curve.push_back(portfolio.value(prices_.prices(0)));
    result.final_weights = portfolio.weights(prices_.prices(0));

    // Convert basis points into decimal cost.
    // Example: 5 bps = 0.0005.
    const double cost_rate = config_.transaction_cost_bps / 10000.0;

    for (std::size_t row = 1; row < prices_.row_count(); ++row) {
        // This is the key polymorphism line.
        // BacktestEngine does not know the concrete strategy type. It only
        // calls the virtual rebalance() function.
        std::vector<Trade> trades = strategy.rebalance(
            row,
            portfolio,
            prices_,
            target_weights_,
            cost_rate
        );

        // Store trades and turnover generated by the strategy.
        for (const auto& trade : trades) {
            result.total_turnover += trade.turnover;
            result.trades.push_back(trade);
        }

        // Record portfolio state after any trades on this date.
        result.dates.push_back(prices_.date(row));
        result.equity_curve.push_back(portfolio.value(prices_.prices(row)));
        result.final_weights = portfolio.weights(prices_.prices(row));
    }

    fill_daily_returns(result);
    return result;
}

void BacktestEngine::fill_daily_returns(BacktestResult& result) {
    result.daily_returns.clear();

    if (result.equity_curve.size() < 2) {
        return;
    }

    result.daily_returns.reserve(result.equity_curve.size() - 1);

    for (std::size_t i = 1; i < result.equity_curve.size(); ++i) {
        const double yesterday = result.equity_curve[i - 1];
        const double today = result.equity_curve[i];
        result.daily_returns.push_back(today / yesterday - 1.0);
    }
}

